name: logger_module
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  logger: ^2.2.0
  stack_trace: ^1.11.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.logger_module
    iosBundleIdentifier: com.example.loggerModule
